name: release

on:
  release:
    types: [created]

jobs:
  release:
    name: publish ${{ matrix.name }}
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            suffix: windows-x86_64
            archive: zip
            name: windows

          - target: x86_64-unknown-linux-gnu
            suffix: linux-x86_64
            archive: tar.xz
            name: linux

          - target: x86_64-apple-darwin
            suffix: darwin-x86_64
            archive: tar.gz
            name: mac-intel

          - target: aarch64-apple-darwin
            suffix: darwin-aarch64
            archive: tar.gz
            name: mac-arm64

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - uses: xhaiker/rust-release.action@v1.0.0
        name: build ${{ matrix.name }}
        with:
          rust_target: ${{ matrix.target }}
          archive_suffix: ${{ matrix.suffix }}
          archive_types: ${{ matrix.archive }}
          extra_files: "README.md LICENSE"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
